config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from usuarios.views import logout_view
from django.conf import settings
from django.conf.urls.static import static
from core.views import home

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', home, name='home'),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="usuarios/login.html"),
        name="login"
    ),

    path("logout/", logout_view, name="logout"),

    path("usuarios/", include("usuarios.urls")),
    path("productos/", include("productos.urls")),
    path("reportes/", include("reportes.urls")),
    path("mensajeria/", include("mensajeria.urls")),
    #path("", include("core.urls")),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="usuarios/password_reset.html"
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="usuarios/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="usuarios/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="usuarios/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/core/urls.py
from django.urls import path
from . import views

"""
urlpatterns = [
    path("", views.home, name="home"),
]
"""

config/mensajeria/urls.py
from django.urls import path
from . import views

app_name = 'mensajeria'

urlpatterns = [
    path('conversaciones/', views.lista_conversaciones, name='conversaciones'),
    path('buscar-cliente/', views.buscar_cliente_chat, name='buscar_cliente'),
    path('chat/', views.chat, name='chat_default'),
    path('chat/<int:user_id>/', views.chat, name='chat'),
    path("soporte/", views.soporte_conversaciones, name="soporte_conversaciones"),
]

config/mensajeria/models.py
from django.conf import settings
from django.db import models

class Message(models.Model):
    sender = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='sent_messages'
    )
    receiver = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='received_messages'
    )
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ['timestamp']

    def __str__(self):
        return f"{self.sender} → {self.receiver}: {self.content[:20]}"

config/mensajeria/forms.py
from django import forms

class BuscarClienteForm(forms.Form):
    query = forms.CharField(
        label="Buscar cliente por RUT o username",
        max_length=50,
        required=True
    )

config/mensajeria/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.db.models import Q, Max
from usuarios.backends import Usuario
from .models import Message
from django.contrib import messages
from .models import Message
from .forms import BuscarClienteForm

User = get_user_model()

def buscar_cliente_chat(request):
    # Solo atención al cliente
    if not request.user.is_authenticated or request.user.tipo_cliente != "atencion_cliente":
        messages.error(request, "No tienes permiso para acceder a esta sección.")
        return redirect("dashboard")

    form = BuscarClienteForm(request.GET or None)
    resultados = Usuario.objects.none()

    if form.is_valid():
        query = form.cleaned_data["query"].strip()

        resultados = Usuario.objects.filter(
            Q(rut__icontains=query) |
            Q(username__icontains=query)
        ).exclude(tipo_cliente="atencion_cliente")

        if not resultados.exists():
            messages.warning(request, "No se encontró ningún cliente con ese RUT o usuario.")

    return render(request, "mensajeria/buscar_cliente.html", {
        "form": form,
        "resultados": resultados,
    })
    
def iniciar_chat_con_cliente(request, id_cliente):
    if request.user.tipo_cliente != "atencion_cliente":
        messages.error(request, "No tienes permiso.")
        return redirect("dashboard")

    cliente = get_object_or_404(Usuario, id=id_cliente)

    # Buscar chat existente
    chat, creado = Message.objects.get_or_create(
        usuario=cliente,
        soporte=request.user
    )

    return redirect("chat_detalle", chat_id=chat.id)


# Selecciona automáticamente al soporte
def obtener_agente_soporte():
    return User.objects.filter(tipo_cliente="atencion_cliente").order_by('?').first()

def lista_conversaciones(request):
    user = request.user

    conversaciones = (
        Message.objects.filter(Q(sender=user) | Q(receiver=user))
        .values("sender", "receiver")
        .annotate(last_msg=Max("timestamp"))
        .order_by("-last_msg")
    )

    usuarios_conversando = []
    ids_agregados = set()

    for conv in conversaciones:
        partner_id = conv["receiver"] if conv["sender"] == user.id else conv["sender"]

        if partner_id not in ids_agregados:
            ids_agregados.add(partner_id)

            partner = User.objects.get(id=partner_id)

            # Contar no leídos de ese usuario → hacia ti
            partner.unread_count = Message.objects.filter(
                sender=partner,
                receiver=user,
                is_read=False
            ).count()

            usuarios_conversando.append(partner)

    return render(request, "mensajeria/lista_conversaciones.html", {
        "usuarios": usuarios_conversando
    })


# ------------------------------------
# Vista del chat
# ------------------------------------
def chat(request, user_id=None):

    user = request.user

    # 1. Cliente sin user_id → asignar soporte automáticamente
    if user.tipo_cliente != "atencion_cliente" and user_id is None:
        soporte = obtener_agente_soporte()
        if not soporte:
            # Para evitar que el template se rompa
            other_user = request.user  

            return render(request, "mensajeria/chat.html", {
                "mensajes": [],
                "other_user": other_user,
                "error": "No hay agentes de soporte disponibles."
            })
        other_user = soporte

    # 2. Soporte sin user_id → NO puede abrir chat sin elegir cliente
    elif user.tipo_cliente == "atencion_cliente" and user_id is None:
        return redirect("mensajeria:soporte_conversaciones")

    # 3. Chat normal con user_id
    else:
        other_user = get_object_or_404(User, id=user_id)

    # Obtener mensajes reales
    mensajes = Message.objects.filter(
        Q(sender=user, receiver=other_user) |
        Q(sender=other_user, receiver=user)
    ).order_by("timestamp")

    # Marcar mensajes recibidos como leídos
    mensajes.filter(receiver=user).update(is_read=True)

    # Enviar mensaje
    if request.method == "POST":
        texto = request.POST.get("mensaje") or request.POST.get("content")

        if texto and texto.strip():
            Message.objects.create(
                sender=user,
                receiver=other_user,
                content=texto.strip()
            )

        return redirect("mensajeria:chat", user_id=other_user.id)

    return render(request, "mensajeria/chat.html", {
        "mensajes": mensajes,
        "other_user": other_user
    })


def soporte_conversaciones(request):
    conversaciones = (
        Message.objects.filter(receiver=request.user)
        .values("sender")
        .annotate(last_msg=Max("timestamp"))
        .order_by("-last_msg")
    )

    clientes = []
    for conv in conversaciones:
        cliente = User.objects.get(id=conv["sender"])
        cliente.unread_count = Message.objects.filter(
            sender=cliente,
            receiver=request.user,
            is_read=False
        ).count()
        clientes.append(cliente)

    return render(request, "mensajeria/soporte_conversaciones.html", {
        "clientes": clientes
    })

config/mensajeria/templates/mensajeria/buscar_cliente.html
{% extends 'core/base.html' %}

{% block title %}Buscar Cliente - Atención al Cliente{% endblock %}

{% block content %}
<div class="container">
    <a href="{% url 'dashboard' %}" class="btn btn-secondary"

   style="
        display: inline-flex;
        align-items: center;
        gap: 6px;
        text-decoration: none;
        color: #000000b3;
        font-weight: 600;
        margin-bottom: 1rem;
   ">
    ← Volver
    </a>
    <h2>Buscar cliente para iniciar chat</h2>

    <form method="GET" class="form-inline mb-3">
        {{ form.query }}
        <button type="submit" class="btn btn-primary">Buscar</button>
    </form>

    <hr>

    {% if resultados %}
        <h3>Resultados</h3>

        <table class="table">
            <tr>
                <th>Usuario</th>
                <th>RUT</th>
                <th>Acción</th>
            </tr>

            {% for u in resultados %}
                <tr>
                    <td>
                        <a href="{% url 'mensajeria:chat' u.id %}">
                            {{ u.username }} ({{ u.rut }})
                        </a>
                    </td>
                    <td>{{ u.rut }}</td>
                    <td>
                        <a href="{% url 'mensajeria:chat' u.id %}" class="btn btn-success">
                            Abrir Chat
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}

</div>
{% endblock %}

config/mensajeria/templates/mensajeria/chat.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <a href="{% url 'mensajeria:conversaciones' %}" class="btn btn-secondary"

   style="
        display: inline-flex;
        align-items: center;
        gap: 6px;
        text-decoration: none;
        color: #000000b3;
        font-weight: 600;
        margin-bottom: 1rem;
   ">
    ← Volver
    </a>

    <div class="dashboard-card">

        <h1 class="dashboard-title">Chat con {{ other_user.username }}</h1>
        <p class="dashboard-welcome">
            Aquí puedes conversar con Atención al Cliente.
        </p>

        <!-- Caja del Chat -->
        <div class="card" style="margin-top: 1.5rem; padding: 1.5rem;">

            <!-- Historial de mensajes -->
            <div id="chat-box" 
                style="
                    height: 350px;
                    overflow-y: auto;
                    padding-right: 10px;
                    display: flex;
                    flex-direction: column;
                    gap: 1rem;
                ">
                
                {% for msg in mensajes %}
                    {% if msg.sender.id == user.id %}
                        <!-- Mensaje enviado -->
                        <div style="
                            align-self: flex-end;
                            background: #e1f7e7;
                            color: hsl(109, 94%, 25%);
                            padding: 0.7rem 1rem;
                            max-width: 75%;
                            border-radius: 18px;
                        ">
                            {{ msg.content }}
                        </div>
                    {% else %}
                        <!-- Mensaje recibido -->
                        <div style="
                            align-self: flex-start;
                            background: #f1f1f1;
                            color: #1f2933;
                            padding: 0.7rem 1rem;
                            max-width: 75%;
                            border-radius: 18px;
                        ">
                            {{ msg.content }}
                        </div>
                    {% endif %}
                {% empty %}
                    <p>No hay mensajes todavía.</p>
                {% endfor %}
            </div>

            <!-- Formulario de envío -->
            <form method="POST" action="{% url 'mensajeria:chat' other_user.id %}">
                {% csrf_token %}

                <div class="form-group">
                    <label class="form-label">Tu mensaje</label>
                    <textarea name="content" 
                        style="
                            width: 100%;
                            min-height: 80px;
                            padding: 0.7rem 0.9rem;
                            border-radius: 12px;
                            border: 1px solid #cbd2e1;
                            font-size: 0.9rem;
                            resize: vertical;
                        "
                        required></textarea>
                </div>

                <button type="submit" class="btn btn-primary" style="margin-top: 0.6rem;">
                    Enviar mensaje
                </button>
            </form>

        </div>

    </div>
</div>

<script>
    // Cuando el chat cargue, baja automáticamente al final
    const box = document.getElementById("chat-box");
    if (box) {
        box.scrollTop = box.scrollHeight;
    }
</script>

{% endblock %}

config/mensajeria/templates/mensajeria/lista_conversaciones.html
{% extends "core/base.html" %}
{% block content %}

<div class="container">
    <a href="{% url 'dashboard' %}" class="btn btn-secondary"

   style="
        display: inline-flex;
        align-items: center;
        gap: 6px;
        text-decoration: none;
        color: #000000b3;
        font-weight: 600;
        margin-bottom: 1rem;
   ">
    ← Volver
    </a>
    <div class="card">
        <div class="title">
           <h2 class="titulo">Mis Conversaciones</h2>
        </div>


        {% if usuarios %}
            <ul class="lista">
                {% for usuario in usuarios %}
                <li class="item">
                    <a class="btn btn-fourth" href="{% url 'mensajeria:chat' usuario.id %}">
                        {{ usuario.username }}
                        {% if usuario.unread_count > 0 %}
                            <strong style="color:red;">
                                ({{ usuario.unread_count }} nuevos)
                            </strong>
                        {% endif %}
                    </a>
                </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No tienes conversaciones todavía.</p>
        {% endif %}

        <div style="margin-top: 20px; text-align:center;">
            <a href="{% url 'mensajeria:chat_default' %}" class="btn btn-secondary">
                Hablar con Soporte
            </a>
        </div>
    </div>

</div>

{% endblock %}

config/mensajeria/templates/mensajeria/soporte_conversaciones.html
{% extends "core/base.html" %}
{% block content %}

<div class="container">
    <a href="{% url 'dashboard' %}" class="btn btn-secondary"

   style="
        display: inline-flex;
        align-items: center;
        gap: 6px;
        text-decoration: none;
        color: #000000b3;
        font-weight: 600;
        margin-bottom: 1rem;
   ">
    ← Volver
    </a>
    <div class="card">

        <h2 class="titulo">Clientes que solicitaron soporte</h2>

        {% if clientes %}
        <ul class="lista">
            {% for cliente in clientes %}
                <li class="item">
                    <a class="link" href="{% url 'mensajeria:chat' cliente.id %}">
                        {{ cliente.username }}
                        {% if cliente.unread_count > 0 %}
                            <strong style="color:red;">
                                ({{ cliente.unread_count }} nuevos)
                            </strong>
                        {% endif %}
                    </a>
                </li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No hay mensajes nuevos.</p>
        {% endif %}

    </div>
</div>

{% endblock %}